/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formulario;

import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Liches
 */
public class pnl_busqueda extends javax.swing.JPanel {

    File f = null;
    String path = null;
    String fname = null;
    int s = 0;
    byte[] pimage = null;
    ImageIcon image = null;
    Image img2 = null;
    Image mm = null;

    /**
     * Creates new form pnl_busqueda_asistente
     */
    public pnl_busqueda() {
        initComponents();
        consulta();
    }

    public void consulta() {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            DefaultTableModel dtm = new DefaultTableModel();
            table.setModel(dtm);

            dtm.setColumnIdentifiers(new Object[]{"ID", "MATERIAL", "MARCA", "MODELO", "CANTIDAD", "PRECIO"});
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/inventario_labcel", "root", "");
            Statement comm = con.createStatement();
            ResultSet rs = comm.executeQuery("SELECT * FROM `productos`");

            while (rs.next()) {
                dtm.addRow(new Object[]{rs.getString("id"), rs.getString("material"), rs.getString("marca"), rs.getString("modelo"), rs.getInt("cantidad"), rs.getInt("precio")});
            }

            rs.close();

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Ocurrió un error.\nContacte con el administrador." + "\nError: " + ex.toString(), "ERROR", JOptionPane.ERROR_MESSAGE);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(pnl_busqueda.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void icon() {
        ImageIcon icono;
        icono = new ImageIcon(getClass().getResource("/imagenes/imagen.png"));
        Icon ico = new ImageIcon(icono.getImage().getScaledInstance(icono.getIconWidth(), icono.getIconHeight(), Image.SCALE_DEFAULT));
        btn_mimagen.setIcon(ico);
    }

    public String id(String material, String marca, String modelo) {
        String id = "";
        material = txt_material.getText();
        marca = txt_marca.getText();
        modelo = txt_modelo.getText();

        String submaterial = material.substring(0, 3);

        if (marca.length() == 2) {
            marca = marca + "X";
        } else {
            if (marca.length() == 1) {
                marca = marca + "XX";
            } else {
                if (marca.length() == 0) {
                    marca = "XXX";
                }
            }
        }

        if (modelo.length() == 2) {
            modelo = modelo + "X";
        } else {
            if (modelo.length() == 1) {
                modelo = modelo + "XX";
            } else {
                if (modelo.length() == 0) {
                    modelo = "XXX";
                }
            }
        }

        String submarca = marca.substring(0, 3);
        String submodelo = modelo.substring(0, 3);

        id = submaterial + submarca + submodelo;

        return id.toUpperCase();
    }

    public void clean() {
        txt_id.setText("");
        txt_id.requestFocus();
        txt_material.setText("");
        txt_marca.setText("");
        txt_modelo.setText("");
        txt_cantidad.setText("");
        txt_precio.setText("");
        txt_foto.setText("");
        img2 = null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel13 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        txt_id = new javax.swing.JTextField();
        btn_buscar = new javax.swing.JButton();
        btn_cancelar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_material = new javax.swing.JTextField();
        txt_modelo = new javax.swing.JTextField();
        txt_marca = new javax.swing.JTextField();
        txt_cantidad = new javax.swing.JTextField();
        txt_foto = new javax.swing.JTextField();
        txt_precio = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        btn_modificar = new javax.swing.JButton();
        btn_mimagen = new javax.swing.JButton();
        btn_cimagen = new javax.swing.JButton();
        btn_eliminar = new javax.swing.JButton();
        btn_consultar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        jLabel13.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel13.setText("Mostrar Imagen");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setText("Busqueda de material");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table.setEnabled(false);
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        jLabel7.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel7.setText("ID:");

        txt_id.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        btn_buscar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn_buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/lupa.png"))); // NOI18N
        btn_buscar.setText("Buscar");
        btn_buscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarActionPerformed(evt);
            }
        });

        btn_cancelar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn_cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cancelar1.png"))); // NOI18N
        btn_cancelar.setText("Cancelar");
        btn_cancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("Material");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("Marca");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setText("Modelo");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setText("Cantidad");

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setText("Precio");

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setText("Foto");

        txt_marca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_marcaActionPerformed(evt);
            }
        });

        txt_cantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cantidadActionPerformed(evt);
            }
        });

        txt_foto.setEnabled(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt_material, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_marca, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_modelo, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_precio, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_foto, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 8, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel2)
                .addGap(77, 77, 77)
                .addComponent(jLabel3)
                .addGap(78, 78, 78)
                .addComponent(jLabel4)
                .addGap(68, 68, 68)
                .addComponent(jLabel5)
                .addGap(73, 73, 73)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(45, 45, 45))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(jLabel4)
                        .addComponent(jLabel5)
                        .addComponent(jLabel6)
                        .addComponent(jLabel8)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_material, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txt_marca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txt_modelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txt_precio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txt_foto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(null, "Opciones", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 18)), "", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 18))); // NOI18N

        btn_modificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/editar1.png"))); // NOI18N
        btn_modificar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modificarActionPerformed(evt);
            }
        });

        btn_mimagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/imagen.png"))); // NOI18N
        btn_mimagen.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_mimagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_mimagenActionPerformed(evt);
            }
        });

        btn_cimagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/reemplazar.png"))); // NOI18N
        btn_cimagen.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_cimagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cimagenActionPerformed(evt);
            }
        });

        btn_eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/del.png"))); // NOI18N
        btn_eliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarActionPerformed(evt);
            }
        });

        btn_consultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/buscar1.png"))); // NOI18N
        btn_consultar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_consultarActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel9.setText("Consultar");

        jLabel10.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel10.setText("Modificar");

        jLabel11.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel11.setText("Mostrar Imagen");

        jLabel12.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel12.setText("Cambiar Imagen");

        jLabel14.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel14.setText("Eliminar");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_consultar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_mimagen, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_cimagen, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(20, 20, 20))
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(22, 22, 22))
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(btn_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(30, 30, 30)))
                .addGap(52, 52, 52))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_consultar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(btn_modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(btn_mimagen, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jLabel11)
                .addGap(21, 21, 21)
                .addComponent(btn_cimagen, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addComponent(btn_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_buscar)
                                .addGap(18, 18, 18)
                                .addComponent(btn_cancelar))
                            .addComponent(jLabel1))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel7)
                                .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarActionPerformed
        if (txt_id.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Primero escribe el ID de un registro.", "Advertencia", JOptionPane.WARNING_MESSAGE);
            txt_id.requestFocus();
        } else {
            try {
                Class.forName("com.mysql.jdbc.Driver");
                DefaultTableModel dtm = new DefaultTableModel();
                table.setModel(dtm);

                dtm.setColumnIdentifiers(new Object[]{"ID", "MATERIAL", "MARCA", "MODELO", "CANTIDAD", "PRECIO"});
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost/inventario_labcel", "root", "");
                Statement comm = con.createStatement();
                ResultSet rs = comm.executeQuery("SELECT * FROM `productos` WHERE `id` LIKE '" + txt_id.getText() + "'");
                boolean flag = false;

                while (rs.next()) {
                    dtm.addRow(new Object[]{rs.getString("id"), rs.getString("material"), rs.getString("marca"), rs.getString("modelo"), rs.getInt("cantidad"), rs.getInt("precio")});
                    txt_material.setText(rs.getString("material"));
                    txt_marca.setText(rs.getString("marca"));
                    txt_modelo.setText(rs.getString("modelo"));
                    txt_cantidad.setText(Integer.toString(rs.getInt("cantidad")));
                    txt_precio.setText(Integer.toString(rs.getInt("precio")));

                    byte[] imagedata = rs.getBytes("imagen");

                    if (imagedata != null) {
                        ImageIcon format = new ImageIcon(imagedata);
                        mm = format.getImage();
                        img2 = mm.getScaledInstance(80, 80, Image.SCALE_SMOOTH);
                        image = new ImageIcon(img2);

                        btn_mimagen.setIcon(image);
                    } else {
                        icon();
                    }
                    flag = true;
                }

                if (flag == false) {
                    JOptionPane.showMessageDialog(null, "El registro no existe.", "VERIFICA", JOptionPane.QUESTION_MESSAGE);
                    txt_id.setText("");
                    txt_id.requestFocus();
                }

                if (mm == null) {
                    icon();
                }

                rs.close();

            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Ocurrió un error.\nContacte con el administrador." + "\nError: " + ex.toString(), "ERROR", JOptionPane.ERROR_MESSAGE);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(pnl_busqueda.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_buscarActionPerformed

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
        icon();
        consulta();
        clean();
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_cancelarActionPerformed

    private void txt_marcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_marcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_marcaActionPerformed

    private void txt_cantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cantidadActionPerformed

    private void btn_consultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_consultarActionPerformed
        clean();
        icon();
        consulta();
// TODO add your handling code here:
    }//GEN-LAST:event_btn_consultarActionPerformed

    private void btn_mimagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mimagenActionPerformed
        if (img2 != null) {
            img2 = mm.getScaledInstance(700, 600, Image.SCALE_SMOOTH);
            image = new ImageIcon(img2);
            JOptionPane.showMessageDialog(null, "", "Imagen", JOptionPane.INFORMATION_MESSAGE, image);
        } else {
            JOptionPane.showMessageDialog(null, "No hay imagen que mostrar.", "NO IMAGEN", JOptionPane.INFORMATION_MESSAGE);
        }
// TODO add your handling code here:
    }//GEN-LAST:event_btn_mimagenActionPerformed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        int seleccion = table.rowAtPoint(evt.getPoint());
        txt_id.setText(String.valueOf(table.getValueAt(seleccion, 0)));
        txt_material.setText(String.valueOf(table.getValueAt(seleccion, 1)));
        txt_marca.setText(String.valueOf(table.getValueAt(seleccion, 2)));
        txt_modelo.setText(String.valueOf(table.getValueAt(seleccion, 3)));
        txt_cantidad.setText(String.valueOf(table.getValueAt(seleccion, 4)));
        txt_precio.setText(String.valueOf(table.getValueAt(seleccion, 5)));

        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/inventario_labcel", "root", "");
            Statement comm = con.createStatement();
            ResultSet rs = comm.executeQuery("SELECT * FROM `productos` WHERE `id` LIKE '" + txt_id.getText() + "'");
            while (rs.next()) {
                byte[] imagedata = rs.getBytes("imagen");

                if (imagedata != null) {
                    ImageIcon format = new ImageIcon(imagedata);
                    mm = format.getImage();
                    img2 = mm.getScaledInstance(80, 80, Image.SCALE_SMOOTH);
                    image = new ImageIcon(img2);

                    btn_mimagen.setIcon(image);
                } else {
                    icon();
                    img2 = null;
                }
            }

            rs.close();

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Ocurrió un error.\nContacte con el administrador." + "\nError: " + ex.toString(), "ERROR", JOptionPane.ERROR_MESSAGE);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(pnl_busqueda.class.getName()).log(Level.SEVERE, null, ex);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_tableMouseClicked

    private void btn_cimagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cimagenActionPerformed
        if (txt_id.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Primero selecciona un registro.", "Advertencia", JOptionPane.WARNING_MESSAGE);
            txt_id.requestFocus();
        } else {

            JFileChooser fileChooser = new JFileChooser();
            FileNameExtensionFilter fnwf = new FileNameExtensionFilter("PNG JPG Y JPEG", "png", "jpeg", "jpg");
            fileChooser.addChoosableFileFilter(fnwf);
            int load = fileChooser.showOpenDialog(null);

            if (load == fileChooser.APPROVE_OPTION) {
                f = fileChooser.getSelectedFile();

                path = f.getAbsolutePath();
                txt_foto.setText(path);
                ImageIcon ii = new ImageIcon(path);
                Image img = ii.getImage().getScaledInstance(250, 230, Image.SCALE_SMOOTH);
            }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_cimagenActionPerformed

    private void btn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarActionPerformed
        if (txt_id.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Primero selecciona un registro.", "ADVERTENCIA", JOptionPane.WARNING_MESSAGE);
            txt_id.requestFocus();
        } else {
            while (true) {
                try {
                    int respuesta = JOptionPane.showConfirmDialog(null, "¿Estás seguro de que quieres eliminar el registro?", "Eliminar", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

                    if (respuesta == JOptionPane.YES_OPTION) {

                        try {
                            Class.forName("com.mysql.jdbc.Driver");
                            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/inventario_labcel", "root", "");
                            Statement comm = con.createStatement();
                            comm.executeUpdate("DELETE FROM `productos` WHERE `productos`.`id` = '" + txt_id.getText() + "'");
                            con.close();

                            JOptionPane.showMessageDialog(null, "Registro eliminado correctamente.", "ÉXITO", JOptionPane.INFORMATION_MESSAGE);

                            clean();
                            consulta();
                            icon();
                            break;

                        } catch (Exception e) {
                            JOptionPane.showMessageDialog(null, "Ocurrió un error.\nContacte con el administrador." + "\nError: " + e.toString(), "ERROR", JOptionPane.ERROR_MESSAGE);
                        }

                    } else if (respuesta == JOptionPane.NO_OPTION) {
                        break;
                    }
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Ocurrió un error.\nContacte con el administrador." + "\nError: " + e.toString(), "ERROR", JOptionPane.ERROR_MESSAGE);
                }
            }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_eliminarActionPerformed

    private void btn_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modificarActionPerformed
        if (txt_id.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Primero selecciona un registro.", "ADVERTENCIA", JOptionPane.WARNING_MESSAGE);
            txt_id.requestFocus();
        } else {
            String idcomp = id(txt_material.getText(), txt_marca.getText(), txt_modelo.getText());

            if (txt_foto.getText().equals("")) {
                while (true) {
                    try {
                        int respuesta = JOptionPane.showConfirmDialog(null, "¿Estás seguro de que quieres modificar el registro?", "Modificar", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

                        if (respuesta == JOptionPane.YES_OPTION) {
                            try {
                                String modificacion = "UPDATE productos SET id=?, material=?, marca=?, modelo=?, cantidad=?, precio=? WHERE id=?";
                                Class.forName("com.mysql.jdbc.Driver");
                                Connection con = DriverManager.getConnection("jdbc:mysql://localhost/inventario_labcel", "root", "");
                                PreparedStatement pst = con.prepareStatement(modificacion);
                                pst.setString(1, idcomp);
                                pst.setString(2, txt_material.getText());
                                pst.setString(3, txt_marca.getText());
                                pst.setString(4, txt_modelo.getText());
                                pst.setInt(5, Integer.parseInt(txt_cantidad.getText()));
                                pst.setInt(6, Integer.parseInt(txt_precio.getText()));
                                pst.setString(7, txt_id.getText());
                                pst.executeUpdate();
                                con.close();

                                JOptionPane.showMessageDialog(null, "Registro actualizado correctamente.", "ÉXITO", JOptionPane.INFORMATION_MESSAGE);

                            } catch (ClassNotFoundException ex) {
                                Logger.getLogger(pnl_busqueda.class.getName()).log(Level.SEVERE, null, ex);
                            } catch (SQLException ex) {
                                Logger.getLogger(pnl_busqueda.class.getName()).log(Level.SEVERE, null, ex);
                            }
                            break;
                        } else if (respuesta == JOptionPane.NO_OPTION) {
                            break;
                        }
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, "Ocurrió un error.\nContacte con el administrador." + "\nError: " + e.toString(), "ERROR", JOptionPane.ERROR_MESSAGE);
                    }
                }
            } else {
                while (true) {
                    try {
                        int respuesta = JOptionPane.showConfirmDialog(null, "¿Estás seguro de que quieres modificar el registro?", "Modificar", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

                        if (respuesta == JOptionPane.YES_OPTION) {
                            try {
                                File f = new File(path);
                                InputStream is = new FileInputStream(f);

                                String modificacion = "UPDATE productos SET id=?, material=?, marca=?, modelo=?, cantidad=?, precio=?, imagen=? WHERE id=?";
                                Class.forName("com.mysql.jdbc.Driver");
                                Connection con = DriverManager.getConnection("jdbc:mysql://localhost/inventario_labcel", "root", "");
                                PreparedStatement pst = con.prepareStatement(modificacion);
                                pst.setString(1, idcomp);
                                pst.setString(2, txt_material.getText());
                                pst.setString(3, txt_marca.getText());
                                pst.setString(4, txt_modelo.getText());
                                pst.setInt(5, Integer.parseInt(txt_cantidad.getText()));
                                pst.setInt(6, Integer.parseInt(txt_precio.getText()));
                                pst.setBlob(7, is);
                                pst.setString(8, txt_id.getText());
                                pst.executeUpdate();
                                con.close();

                                JOptionPane.showMessageDialog(null, "Registro actualizado correctamente.", "ÉXITO", JOptionPane.INFORMATION_MESSAGE);

                            } catch (ClassNotFoundException ex) {
                                Logger.getLogger(pnl_busqueda.class.getName()).log(Level.SEVERE, null, ex);
                            } catch (SQLException ex) {
                                Logger.getLogger(pnl_busqueda.class.getName()).log(Level.SEVERE, null, ex);
                            } catch (FileNotFoundException ex) {
                                Logger.getLogger(pnl_busqueda.class.getName()).log(Level.SEVERE, null, ex);
                            }
                            break;
                        } else if (respuesta == JOptionPane.NO_OPTION) {
                            break;
                        }
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, "Ocurrió un error.\nContacte con el administrador." + "\nError: " + e.toString(), "ERROR", JOptionPane.ERROR_MESSAGE);
                    }
                }
            }
            consulta();
            txt_id.setText(idcomp);
            // TODO add your handling code here:
    }//GEN-LAST:event_btn_modificarActionPerformed
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_buscar;
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JButton btn_cimagen;
    private javax.swing.JButton btn_consultar;
    private javax.swing.JButton btn_eliminar;
    private javax.swing.JButton btn_mimagen;
    private javax.swing.JButton btn_modificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table;
    private javax.swing.JTextField txt_cantidad;
    private javax.swing.JTextField txt_foto;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_marca;
    private javax.swing.JTextField txt_material;
    private javax.swing.JTextField txt_modelo;
    private javax.swing.JTextField txt_precio;
    // End of variables declaration//GEN-END:variables
}
